// Generated by Wrangler on Mon Aug 05 2024 19:07:56 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	HEARTHOOK_CHECKINS: KVNamespace;
	HEARTHOOK_INTERVAL: 3;
	HEARTHOOK_NOTIF_ABANDON: true;
	PUSHOVER_DEVICE: "";
	PUSHOVER_PRIORITY: "";
	PUSHOVER_TTL: "";
	HEARTHOOK_SECRET: string;
	PUSHOVER_TOKEN: string;
	PUSHOVER_USER_KEY: string;
}
